import requests
import json
import time
import asyncio
import sys
import concurrent.futures

from clipper_admin import ClipperConnection, KubernetesContainerManager

# Connect to clipper
kmanager = KubernetesContainerManager()
clipper_conn = ClipperConnection(kmanager)
clipper_conn.connect()

# Get query address
addr = clipper_conn.get_query_addr()
# addr = 'ec2-52-77-234-217.ap-southeast-1.compute.amazonaws.com:32584'

#metrics = kmanager.get_metric_addr()
# print('Got metrics address: ', metrics)
print('Got query endpoint address: ', addr)

# Just set the current query address
# addr = 'ec2-54-169-144-111.ap-southeast-1.compute.amazonaws.com:32211'
# addr = '54.169.144.111:32068'
# Setup data for the requests
test_doc = ['CONFIDENTIALITY AGREEMENTCONFIDENTIALITY AGREEMENT', 'THIS AGREEMENT is made as of 10 October 2018', "L'OREAL MALAYSIA SDN BHD (Company No.:", '328418-A), a private limited company incorporated under the laws of Malaysia, whose registered office is located at Level 8, 13A and 15,', 'Uptown 2, No. 2', 'Jalan SS21/37, Damansara Uptown, Petaling Jaya, 47400 Selangor Darul Ehsan ("L\'Oreal Malaysia"); AND L\'OREAL SINGAPORE PTE LTD (Company No.:', '199001413D), a private limited company incorporated under the laws of Singapore, whose registered office is located at 1 George Street #19-01/03, One George Street, Singapore 049145', 'Collectively referred to as "L\'Oreal".', 'AND CXA SINGAPORE PTE LTD (Company No.: 199503006R), a private limited company incorporated under the laws of Singapore, whose business address is located at 401 Commonwealth Drive, #05-03/05, Haw Par Technocentre, Singapore 149598 (the "Receiving Party").', 'L\'Oreal is conducting an assessment to select a vendor to study, design and implement a flexible benefits system for L\'Oreal Malaysia and Singapore ("assessment").', 'The Receiving Party is a participant of the assessment for a vendor to study, design and implement a flexible benefits system for L\'Oreal Malaysia and Singapore ("Project").', "As part of the assessment and selection process, L'Oreal will be conducting a series of discussions and follow up meetings with the Receiving Party.", "L'Oreal will also be sharing with the Receiving Party materials and information of a confidential nature and wish to protect such information in the manner set out in this Agreement.", "L'Oreal is desirous that all or any materials or information to be provided by it to the Receiving Party shall be kept strictly confidential by the Receiving Party.", 'NOW IT IS HEREBY AGREED AS FOLLOWS:- 1.', 'Definitions "Purpose" shall mean any discussions and negotiations or activities between or within the parties concerning or in connection with the assessment and Project. "', 'Confidential Information" shall mean any information, documents, materials and data, whether in oral, written, visual or electronic form, concerning the assessment, Project and/or L\'Oreal which information, documents, materials and data shall include, without limitation, relating to the brands or the business of L\'OrÃ©al, financial statements and reports, legal and organizational documentation, contracts, analyses, reports, compilations, memoranda, notes, ideas, know-how, concepts, trade secrets, business information and all other intellectual property, all copies, notes and records and all related information generated by the Receiving Party based on or arising out of any such, whether before or after the date of this Agreement.', 'Notwithstanding the foregoing, the term "Confidential Information" shall not include information which: a) Prior to the disclosure to the Receiving Party was in the public domain in any way without breach of this Agreement by the Receiving Party; or b) Is lawfully in possession of the Receiving Party prior to the receipt of any information from L\'Oreal.', 'Handling of Confidential Information By executing this Agreement, the Receiving Party agreed and undertakes to L\'Oreal: a) to take and to procure that all the Receiving Party\'s officers, employees, agents, professional advisors, affiliates and consultants (each an "Authorised Person") take all steps as may be necessary, prudent or desirable to maintain and safeguard: the confidentiality of the Confidential Information; and the confidentiality of evaluation and management of the Project, and the discussions and negotiations pertaining to the Project.', "b) to use the Confidential Information solely for the Purpose; c) to maintain the Confidential Information in confidence and shall exercise in relation thereto no lesser security measures and degree of care than those which the Receiving Party applies to its own confidential information; d) not to photocopy, reproduce or duplicate the Confidential Information or any part thereof except to the extent reasonably necessary for the Purpose and with the prior authorization of L'Oreal; e) to obtain the prior authorization of L'Oreal before disclosing the Confidential Information to an Authorised Person or any third parties involved in the assessment and Project; f) to ensure that the Authorised Person or third party to whom disclosure of Confidential Information is made is fully aware in advance of the Receiving Party's obligations under this Agreement and is bound by the terms hereunder; g) not to use the Confidential Information in any fashion or manner detrimental to the interest of L'Oreal; h) to indemnify L'Oreal from and against all claims, costs, expenses, loss or damage (including but not limited to legal costs), which may arise directly or indirectly from the unauthorised disclosure or use of the Confidential Information by the Receiving Party, its Authorised Persons or third parties which have been granted authorized access to the Confidential Information; i) to immediately notify L'Oreal in writing of any proceedings or action taken by any third party which could result in the Receiving Party or any of its Authorized Person(s) becoming compelled to disclose the Confidential Information; j) the Receiving Party and its Authorised Person(s) shall not, directly or indirectly, contact or speak to any of L'Oreal's agencies, customers, business contacts or third parties which have provided any Confidential Information to L'Oreal without the prior written consent of L'Oreal; k) shall not, without the prior written consent of L'Oreal, make or authorise any advertisement, public announcement or press release referring to or relating to this Agreement or any matter relating to the assessment and Project.", "Notwithstanding the foregoing provisions, if the Receiving Party or any of its Authorised Persons is compelled to disclose any Confidential Information pursuant to a valid order of a court of competent jurisdiction or is otherwise required by legal or judicial process to disclose Confidential Information, the Receiving Party or such Authorised Person may disclose such portion of the Confidential Information as the Receiving Party or such Authorised Person is legally required to disclose, provided the Receiving Party shall first give notice to L'Oreal in order to allow L'Oreal to obtain a protective order and shall reasonably cooperate with L'Oreal in connection therewith.", 'Return/Destruction of Confidential Information', "If required by written notice from L'Oreal, the Receiving Party agrees that within fourteen (14) business days of such notice: (a) to return to L'Oreal all Confidential Information (and all and any copies thereof); (b) to expunge all Confidential Information from any computer, word processor, electronic and mobile device into which it was programmed by the Receiving Party or its Authorised Persons; and (c) destroy all notes, analyses or memoranda containing Confidential Information prepared by the Receiving Party or any of its Authorised Persons.", "All rights in Confidential Information are reserved by L'OrÃ©al and no rights or obligations other than those expressly recited herein are granted or to be implied from this Agreement.", 'In particular, no licence is hereby granted directly or indirectly under any invention, discovery, patent, copyright or other industrial property right now or in the future held, made, obtained or licensable by either party.', 'Nothing in this Agreement or its operation shall preclude, impair or restrict either party from continuing to engage in its business otherwise than in breach of the terms of this Agreement.', 'Remedies for Breach', "It is further understood and agreed that any breach of the obligations contained herein could cause L'Oreal irreparable injury and that monetary damages would not be adequate remedy for any such breach.", "In the event of such breach or threatened breach by the Receiving Party or its Authorized Person(s) of any provisions of this Agreement, L'Oreal shall be entitled to injunctive relief in any court of competent jurisdiction restraining the Receiving Party or its Authorized Person(s) from breaching the terms hereof or from disclosing any Confidential Information or notes to any person.", "The Receiving Party hereby undertake to fully indemnify L'Oreal for any costs, claims, demands or liabilities of whatsoever nature directly arising out of a breach of the Receiving Party's obligations in whatever jurisdiction (or that of your Authorized Persons) hereunder.", 'Each notice or communication to be made hereunder shall be made in writing.', 'Any notice or communication under this Agreement shall be delivered personally, sent by prepaid registered post, by hand or by courier, or by facsimile transmission to the contact details specified below or to such other contact details as the respective Party may have forwarded to the other Party hereto in writing.', 'The date of service shall be deemed to be the day following the day on which the notice was transmitted or posted as the case may be.', 'Assignment This Agreement is personal to the parties and shall not be assigned or otherwise transferred in whole or in part by either party without the prior written consent of the other party.', 'Entire Agreement, Governing Law and Jurisdiction', 'This Agreement constitutes the entire agreement and understanding between the parties in respect of Confidential Information and supersedes all previous agreements, understandings and undertakings in such respect.', 'The interpretation, construction and effect of this Agreement shall be governed and construed in all respects in accordance with the Laws of Malaysia and the parties hereby submit to the exclusive jurisdiction of the Malaysian Courts.', 'This agreement may be executed in any number of counterparts or duplicates, each of which shall be an original, and such counterparts or duplicates shall together constitute one and the same agreement.', 'This Agreement may be amended or modified only by mutual agreement of authorized representatives of the parties in writing.', 'The obligations contained in this Agreement shall continue in force for a period of one (1) year from the date of this Agreement.', '[End of Page] EXECUTION IN WITNESS', 'WHEREtensorflow==1.3.0OF the parties hereto have executed this Agreement through their duly authorized representatives on the day and year written above.', "Sigtensorflow==1.3.0ned by ) for and on behalf of ) L'OREAL MALAYSIA SDN BHD )", '(Company No. 328418-A) )', 'In the presence of: - ) ................. Name: .......tensorflow==1.3.0..........', "Name: Signed by ) for and on behalf of ) L'OREAL SINGAPORE PTE LTD )", '(Company No. 199001413D) )', 'In the presence of: - ) ...tensorflow==1.3.0.............. Name: .................', 'Name: Signed by ) for and on behalf of ) CXA SINGAPORE PTE LTD ) (', 'Company No.: 199503006R) )', 'In the presence of: - ) ................. Name: ..................']
req_json = json.dumps({
    "input_batch": test_doc
})
headers = {"Content-type": "application/json"}
#apps = clipper_conn.get_all_apps()
apps = ['risk-indemnity', 'rpo-non-use', 'nda-right-to-indep-dev', 'risk-warranties-general', 'boiler-variation', 'ci-def-list', 'ci-def-marked', 'rpo-return', 'boiler-no-partner', 'disputes-disp-reso', 'boiler-ent-agmt', 'ci-def-marked-reduce-oral', 'rpo-no-copies', 'disputes-gov-law', 'ci-def', 'rpo-resp3-p-breach', 'boiler-severability', 'restraint-non-solicit', 'term-general', 'term-definite', 'rpo-stof-care', 'dright-ownership-info', 'boiler-waiver', 'rpo-disc-limits', 'nda-no-licence-granted', 'boiler-counterparts', 'nda-commit-contract', 'term-survival-clause', 'ci-std-except', 'disputes-remedy', 'rpo-notify-breach']
print(apps)

def predict(index, app):
    try:
        t1 = time.time()
        endpoint = "http://" + addr + "/{0}/predict".format(app)
        # print(endpoint, headers, req_json)
        response = requests.post(endpoint, headers=headers, data=req_json)
        # print(response.content)
        print('{0} Query successful for {1} endpoint and completed in {2} seconds'.format(index, app, time.time() - t1))
    except requests.exceptions.RequestException as e:
        print(e)
        print('{0} Query failed for {1} endpoint.'.format(index, app))

async def getStuff():
    with concurrent.futures.ThreadPoolExecutor(max_workers=35) as executor:
        loop = asyncio.get_event_loop()
        futures = [
            loop.run_in_executor(
                executor,
                predict,
                index,
                app
            )
            for index, app in enumerate(apps)
        ]
        for response in await asyncio.gather(*futures):
            pass


t0 = time.time()
loop = asyncio.get_event_loop()
loop.run_until_complete(getStuff())
t1 = time.time()
print("Analysis complete. ASYNC Query of {0} endpoints completed in {1} seconds.".format(len(apps), t1 - t0))


# t2 = time.time()
# for index, app in enumerate(apps):
    # try:
        # t1 = time.time()
        # endpoint = "http://" + addr + "/{0}/predict".format(app)
        # response = requests.post(endpoint, headers=headers, data=req_json)
        # print(response.content)
        # print('{0} Query successful for {1} endpoint and completed in {2} seconds'.format(index, app, time.time() - t1))
    # except:
        # print('{0} Query failed for {1} endpoint.'.format(index, app))

# t3 = time.time()

# print("Analysis complete. Sequential Query of {0} endpoints completed in {1} seconds.".format(len(apps), t3 - t2))
